### ISSUE TITLE
Connection error in windows 10

### ISSUE THREAD

**Issue by chutao** [nomnivore/ollama.nvim#19]
I cannot connect to my ollama serve, and met this error:
![error](https://github.com/nomnivore/ollama.nvim/assets/1450401/3a5bfbc3-0fb4-451a-844f-11c92bec67f4)

after some digging, I figured out that it was caught by curl from system. When I ran command coped from log, I got this: 

> curl -sSL -D C:\Users\Eric\AppData\Local\Temp\plenary_curl_cb9c41a5.headers --compressed -X GET http://192.168.0.181:11434/api/tags
> curl: option --compressed: the installed libcurl version doesn't support this

when I removed '--compressed' flag, It works:

> curl -sSL -D C:\Users\Eric\AppData\Local\Temp\plenary_curl_cb9c41a5.headers -X GET http://192.168.0.181:11434/api/tags
> {"models":[{"name":"llama2:latest","modified_at":"2024-01-16T10:46:47.812037511Z","size":3826793677,"digest":"78e26419b4469263f75331927a00a0284ef6544c1975b826b15abdaef17bb962","details":{"format":"gguf","family":"llama","families":["llama"],"parameter_size":"7B","quantization_level":"Q4_0"}},{"name":"mistral:latest","modified_at":"2024-01-17T05:39:41.463682696Z","size":4109865159,"digest":"61e88e884507ba5e06c49b40e6226884b2a16e872382c2b44a42f2d119d804a5","details":{"format":"gguf","family":"llama","families":["llama"],"parameter_size":"7B","quantization_level":"Q4_0"}}]}

I am not familiar with Lua language, can you please tell me how to change this behavior? Or I will have to install a new version of curl that support this feature and change PATH environment variable to solve this problem.

**Comment by nomnivore** [comment]
Hey,

I've not tested this plugin to work with Windows, but it seems the issue you are facing is related to the dependency `plenary`, and more specifically, `libcurl` on Windows.

From my own brief research, it seems you can get around this by installing a version of curl that specifically supports the `--compressed` flag on Windows, so I would start your search there.

If anyone else has insight on this I'd be glad to know!
