### ISSUE TITLE
Is it possible to use ollama in autocomplete mode?

### ISSUE THREAD

**Issue by dpecos** [nomnivore/ollama.nvim#23]
To have a similar interaction to what Copilot does (autocompletes ahead of where you are).

**Comment by nomnivore** [comment]
Not planned for this plugin. If there is another plugin which does OpenAPI-driven autocomplete (ChatGPT), you can try configuring the API url/etc to point to your ollama server, as they have added OpenAPI-compatible endpoints in a recent update.
