### ISSUE TITLE
Streaming response

### ISSUE THREAD

**Issue by traverseda** [nomnivore/ollama.nvim#27]
It would be nice if there was a way to stream responses, instead of waiting for the entire response to return at once.

**Comment by traverseda** [comment]
Reading through the documentation it's clear that this exists, maybe it makes sense to make it the default?

**Comment by nomnivore** [comment]
All of the built-in `display_` actions stream the response in. You can configure your prompts to point to any of these actions according to your needs, including the default prompts.
